### ISSUE TITLE
Unsupported network 'pinterest'. Choose from: twitter.

### ISSUE THREAD

**Issue by CharlyJazz** [richardvenneman/social-url#1]
```
  get '/test/social' do
    message = SocialUrl::Message.new({
      text: 'Hello World',
      url: 'http://example.com',
      hashtags: %w(nature sunset)
    })
    message.pinterest_url
  end
```

Any idea?
Only work with twitter_url

**Comment by richardvenneman** [comment]
Hi @CharlyJazz,

That's really strange! Only thing I can think of is that you're using a version below `0.3.0` (when I added Pinterest).

I just tried it locally and everything works as expected..

```console
 ~  ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]
irb
irb(main):001:0> require 'social_url'
=> true
irb(main):002:0> SocialUrl::VERSION
=> "1.1.0"
irb(main):003:0> message = SocialUrl::Message.new(
irb(main):004:1*   text: 'Hello World',
irb(main):005:1*   url: 'http://example.com',
irb(main):006:1*   hashtags: %w(nature sunset)
irb(main):007:1> )
=> #<SocialUrl::Message:0x007fd8ee00c638 @options={:text=>"Hello%20World", :url=>"http%3A%2F%2Fexample.com", :hashtags=>"nature,sunset", :description=>"Hello%20World", :u=>"http%3A%2F%2Fexample.com"}>
irb(main):008:0> message.pinterest_url
=> "https://www.pinterest.com/pin/create/button/?url=http%3A%2F%2Fexample.com&description=Hello%20World"
irb(main):009:0> message.twitter_url
=> "https://twitter.com/intent/tweet/?text=Hello%20World&url=http%3A%2F%2Fexample.com&hashtags=nature,sunset"
irb(main):010:0> message.facebook_url
=> "https://www.facebook.com/sharer/sharer.php?u=http%3A%2F%2Fexample.com"
irb(main):011:0> message.google_url
=> "https://plus.google.com/share?url=http%3A%2F%2Fexample.com"
```

Which Ruby version do you use? Did you perhaps override the `SocialUrl::NETWORKS` constant? What is your output of `SocialUrl.networks`?

**Comment by CharlyJazz** [comment]
ruby 2.3.1p112
gem 'social-url', '~> 0.1.1'
![screenshot at 2017-03-20 22 33 05](https://cloud.githubusercontent.com/assets/12489333/24130130/393ea778-0dbd-11e7-9f04-fb6f7d2b7025.png)
`  get '/test' do
    message = SocialUrl::Message.new({
      text: 'Hello World',
      url: 'http://example.com',
      hashtags: %w(nature sunset)
    })
    message.facebook_url
  end`

Only work the method 'twitter_url'
bug?

**Comment by richardvenneman** [comment]
Hey @CharlyJazz, I still think it could be that the version you're using is outdated. Could you paste the output of `SocialUrl::VERSION` and `SocialUrl::NETWORKS`?

**Comment by CharlyJazz** [comment]
irb(main):016:0> SocialUrl.networks
=> [:twitter]

irb(main):020:0> SocialUrl::VERSION
=> "0.1.1"

**Comment by richardvenneman** [comment]
You are using an old version which only contains Twitter functionality. The current version is `1.1.0`. Please update your Gemfile to read:

```ruby
gem 'social-url', '~> 1.1.0'
```

**Comment by CharlyJazz** [comment]
Thank.
Btw, this gem is pretty cool.

**Comment by richardvenneman** [comment]
Thanks! I'm glad it's of use to you 😄
